attack(carryOff_GPS_Attack).
attack(terrestrial_Jamming).
attack(evil_Twin_WiFi_Attack).
attack(cellular_Rogue_Base_Station).
attack(sniffing_Network_Traffic).
attack(accessing_Intercepting_Modifying_HTTP_Cookies).
attack(utilizing_RESTs_Trust_in_the_System_Resource_to_Obtain_Sensitive_Data).
attack(cellular_Traffic_Intercept).
attack(sniff_Application_Code).
attack(probe_Audio_and_Video_Peripherals).
attack(wiFi_MAC_Address_Tracking).
attack(wiFi_SSID_Tracking).
attack(cellular_Broadcast_Message_Request).
attack(signal_Strength_Tracking).
attack(tcp_SYN_Scan).
attack(tcp_Connect_Scan).
attack(tcp_FIN_Scan).
attack(tcp_Xmas_Scan).
attack(tcp_Null_Scan).
attack(tcp_ACK_Scan).
attack(tcp_Window_Scan).
attack(tcp_RPC_Scan).
attack(udp_Scan).
attack(padding_Oracle_Crypto_Attack).
attack(cryptanalysis_of_Cellular_Encryption).
attack(xml_Routing_Detour_Attacks).
attack(transaction_or_Event_Tampering_via_Application_API_Manipulation).
attack(content_Spoofing_Via_Application_API_Manipulation).
attack(navigation_Remapping_To_Propagate_Malicious_Content).
attack(aplication_API_Button_Hijacking).
attack(leveraging_Active_Man_in_the_Middle_Attacks_to_Bypass_Same_Origin_Policy).
