severity(carryOff_GPS_Attack, high).
severity(terrestrial_Jamming, high).
severity(evil_Twin_WiFi_Attack, low).
severity(cellular_Rogue_Base_Station, low).
severity(sniffing_Network_Traffic, medium).
severity(accessing_Intercepting_Modifying_HTTP_Cookies, high).
severity(utilizing_RESTs_Trust_in_the_System_Resource_to_Obtain_Sensitive_Data, very_high).
severity(cellular_Traffic_Intercept, low).
severity(sniff_Application_Code, high).
severity(probe_Audio_and_Video_Peripherals, high).
severity(wiFi_MAC_Address_Tracking, low).
severity(wiFi_SSID_Tracking, low).
severity(cellular_Broadcast_Message_Request, low).
severity(signal_Strength_Tracking, low).
severity(tcp_SYN_Scan, low).
severity(tcp_Connect_Scan, low).
severity(tcp_FIN_Scan, low).
severity(tcp_Xmas_Scan, low).
severity(tcp_Null_Scan, low).
severity(tcp_ACK_Scan, low).
severity(tcp_Window_Scan, low).
severity(tcp_RPC_Scan, low).
severity(udp_Scan, low).
severity(padding_Oracle_Crypto_Attack, high).
severity(cryptanalysis_of_Cellular_Encryption, high).
severity(xml_Routing_Detour_Attacks, medium).
severity(transaction_or_Event_Tampering_via_Application_API_Manipulation, medium).
severity(content_Spoofing_Via_Application_API_Manipulation, low).
severity(navigation_Remapping_To_Propagate_Malicious_Content, medium).
severity(aplication_API_Button_Hijacking, medium).
severity(leveraging_Active_Man_in_the_Middle_Attacks_to_Bypass_Same_Origin_Policy, medium).
severity(establish_Rogue_Location, medium).
severity(sniffing_Attacks, medium).
severity(cryptanalysis, very_high).
severity(reflection_Attack_in_Authentication_Protocol, high).
severity(data_Serialization_External_Entities_Blowup, medium).
severity(eavesdropping, medium).
severity(manipulating_Opaque_Client_based_Data_Tokens, medium).



