likelihood(carryOff_GPS_Attack, low).
likelihood(terrestrial_Jamming, low).
likelihood(evil_Twin_WiFi_Attack, medium).
likelihood(cellular_Rogue_Base_Station, low).
likelihood(sniffing_Network_Traffic, high).
likelihood(accessing_Intercepting_Modifying_HTTP_Cookies, high).
likelihood(utilizing_RESTs_Trust_in_the_System_Resource_to_Obtain_Sensitive_Data, medium).
likelihood(cellular_Traffic_Intercept, medium).
likelihood(sniff_Application_Code, low).
likelihood(probe_Audio_and_Video_Peripherals, low).
likelihood(wiFi_MAC_Address_Tracking, low).
likelihood(wiFi_SSID_Tracking, medium).
likelihood(cellular_Broadcast_Message_Request, high).
likelihood(signal_Strength_Tracking, high).
likelihood(tcp_SYN_Scan, medium).
likelihood(tcp_Connect_Scan, medium).
likelihood(tcp_FIN_Scan, medium).
likelihood(tcp_Xmas_Scan, medium).
likelihood(tcp_Null_Scan, medium).
likelihood(tcp_ACK_Scan, medium).
likelihood(tcp_Window_Scan, medium).
likelihood(tcp_RPC_Scan, medium).
likelihood(udp_Scan, medium).
likelihood(padding_Oracle_Crypto_Attack, low).
likelihood(cryptanalysis_of_Cellular_Encryption, high).
likelihood(xml_Routing_Detour_Attacks, high).
likelihood(transaction_or_Event_Tampering_via_Application_API_Manipulation, medium).
likelihood(content_Spoofing_Via_Application_API_Manipulation, low).
likelihood(navigation_Remapping_To_Propagate_Malicious_Content, high).
likelihood(aplication_API_Button_Hijacking, high).
likelihood(leveraging_Active_Man_in_the_Middle_Attacks_to_Bypass_Same_Origin_Policy, medium).
likelihood(establish_Rogue_Location, medium).
likelihood(sniffing_Attacks, medium).
likelihood(cryptanalysis, low).
likelihood(reflection_Attack_in_Authentication_Protocol, high).
likelihood(data_Serialization_External_Entities_Blowup, high).
likelihood(eavesdropping, low).
likelihood(manipulating_Opaque_Client_based_Data_Tokens, high).


