mitigations(carryOff_GPS_Attack, [unspecified]).
mitigations(terrestrial_Jamming, [unspecified]).
mitigations(evil_Twin_WiFi_Attack, [commercial_defensive_technology_that_monitors_for_rogue_WiFi_access_points_man_in_the_middle_attacks_and_anomalous_activity_with_the_mobile_device_baseband_radios]).
mitigations(cellular_Rogue_Base_Station, [passively_monitor_cellular_network_connection_for_real_time_threat_detection_and_logging_for_manual_review]).
mitigations(sniffing_Network_Traffic, [obfuscate_network_traffic_through_encryption_to_prevent_its_readability_by_network_sniffers, employ_appropriate_levels_of_segmentation_to_your_network_in_accordance_with_best_practices]).
mitigations(accessing_Intercepting_Modifying_HTTP_Cookies, [validation_for_cookies, generate_and_validate_MAC_for_cookies, use_SSL_TLS_to_protect_cookie_in_transit, ensure_the_web_server_implements_all_relevant_security_patches]).
mitigations(utilizing_RESTs_Trust_in_the_System_Resource_to_Obtain_Sensitive_Data, [implement_message_level_security_such_as_HMAC_in_the_HTTP_communication, utilize_defense_in_depth_do_not_rely_on_single_security_mechanism_like_SSL, enforce_principle_of_least_privilege]).
mitigations(cellular_Traffic_Intercept, [encryption_of_data_packets_emanating_from_smartphone_to_retransmission_device_with_Suite_B_cryptography]).
mitigations(sniff_Application_Code, [use_SSL_SSH_SCP_to_encrypt_all_communication_between_client_and_server]).
mitigations(probe_Audio_and_Video_Peripherals, [use_allowlist_policy_to_prevent_unknown_code_from_executing_on_system, patch_installed_applications_as_soon_as_new_updates_become_available]).
mitigations(wiFi_MAC_Address_Tracking, [automatic_randomization_of_WiFi_MAC_addresses, frequent_changing_of_handset_and_retransmission_device]).
mitigations(wiFi_SSID_Tracking, [do_not_enable_the_feature_of_Hidden_SSIDs, frequently_change_SSID_to_new_and_unrelated_values]).
mitigations(cellular_Broadcast_Message_Request, [frequent_changing_of_mobile_number]).
mitigations(signal_Strength_Tracking, [unspecified]).
mitigations(tcp_SYN_Scan, [unspecified]).
mitigations(tcp_Connect_Scan, [employ_robust_network_defense_posture_that_includes_IDS_IPS_system]).
mitigations(tcp_FIN_Scan, [use_IDS_IPS_system_with_heuristic_algorithms]).
mitigations(tcp_Xmas_Scan, [employ_robust_network_defensive_posture_that_includes_managed_IDS_IP]).
mitigations(tcp_Null_Scan, [employ_robust_network_defensive_posture_that_includes_managed_IDS_IP]).
mitigations(tcp_ACK_Scan, [unspecified]).
mitigations(tcp_Window_Scan, [unspecified]).
mitigations(tcp_RPC_Scan, [use_IDS_IPS_system]).
mitigations(udp_Scan, [use_firewalls_or_ACLs_which_block_egress_ICMP_error_types]).
mitigations(padding_Oracle_Crypto_Attack, [use_message_authentication_code_or_another_mechanism_to_perform_verification_of_message_authenticity_or_integrity_prior_to_decryption, do_not_leak_information_back_to_user_as_to_any_cryptography_encountered_during_decryption]).
mitigations(cryptanalysis_of_Cellular_Encryption, [use_of_hardened_baseband_firmware_on_retransmission_device_to_detect_and_prevent_the_use_of_weak_cellular_encryption, monitor_cellular_RF_interface_to_detect_the_usage_of_weaker_than_expected_cellular_encryption]).
mitigations(xml_Routing_Detour_Attacks, [specify_maximum_number_intermediate_nodes_for_the_request_and_require_SSL_connections_with_mutual_authentication, use_SSL_for_connections_between_all_parties_with_mutual_authentication]).
mitigations(transaction_or_Event_Tampering_via_Application_API_Manipulation, [unspecified]).
mitigations(content_Spoofing_Via_Application_API_Manipulation, [unspecified]).
mitigations(navigation_Remapping_To_Propagate_Malicious_Content, [unspecified]).
mitigations(aplication_API_Button_Hijacking, [unspecified]).
mitigations(leveraging_Active_Man_in_the_Middle_Attacks_to_Bypass_Same_Origin_Policy, [tunnel_communications_through_secure_proxy, trust_level_separation_for_privileged_or_non_privileged_interactions]).
mitigations(establish_Rogue_Location, [passively_monitor_cellular_network_connection_for_real_time_threat_detection_and_logging_for_manual_review]).
mitigations(sniffing_Attacks, [encrypt_sensitive_information_when_transmitted_on_insecure_mediums_to_prevent_interception]).
mitigations(cryptanalysis, [use_proven_cryptographic_algorithms_with_recommended_key_sizes, ensure_that_the_algorithms_are_used_properly]).
mitigations(reflection_Attack_in_Authentication_Protocol, [server_must_initiate_handshake_by_issuing_challenge, introducing_a_random_nonce_with_each_new_connection]).
mitigations(data_Serialization_External_Entities_Blowup, [implement_custom_resolver_that_has_request_timeout_and_restrict_resources_it_can_retrieve_locally]).
mitigations(eavesdropping, [use_of_antivirus_and_other_security_monitoring_and_detecting_tools, physically_disable_the_microphone_on_your_machine]).
mitigations(manipulating_Opaque_Client_based_Data_Tokens, [protect_client_side_authentication_tokens_for_confidentiality_and_integrity, make_sure_that_session_tokens_use_good_source_of_randomness, perform_validation_on_the_server_side]).

