weaknesses(carryOff_GPS_Attack, [insufficient_Verification_of_Data_Authenticity]).
weaknesses(terrestrial_Jamming, [improper_Authentication]).
weaknesses(evil_Twin_WiFi_Attack, [channel_Accessible_by_Non_Endpoint]).
weaknesses(cellular_Rogue_Base_Station, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(sniffing_Network_Traffic, [missing_Encryption_of_Sensitive_Data]).
weaknesses(accessing_Intercepting_Modifying_HTTP_Cookies, [missing_Encryption_of_Sensitive_Data, improper_Input_Validation, cleartext_Storage_of_Sensitive_Information_in_a_Cookie, session_Fixation, broken_Authentication_and_Session_Management, client_Side_Enforcement_of_Server_Side_Security, external_Control_of_Critical_State_Data]).
weaknesses(utilizing_RESTs_Trust_in_the_System_Resource_to_Obtain_Sensitive_Data, [channel_Accessible_by_Non_Endpoint, improper_Authentication, broken_Authentication_and_Session_Management, protection_Mechanism_Failure]). 
weaknesses(cellular_Traffic_Intercept, [missing_Encryption_of_Sensitive_Data]).
weaknesses(sniff_Application_Code, [cleartext_Transmission_of_Sensitive_Information, missing_Encryption_of_Sensitive_Data, cleartext_Storage_of_Sensitive_Information_in_Executable, protection_Mechanism_Failure, insecure_Cryptographic_Storage]).
weaknesses(probe_Audio_and_Video_Peripherals, [privilege_Defined_With_Unsafe_Actions]).
weaknesses(wiFi_MAC_Address_Tracking, [insertion_of_Sensitive_Information_Into_Sent_Data, channel_Accessible_by_Non_Endpoint]).
weaknesses(wiFi_SSID_Tracking, [insertion_of_Sensitive_Information_Into_Sent_Data, channel_Accessible_by_Non_Endpoint]).
weaknesses(cellular_Broadcast_Message_Request, [insertion_of_Sensitive_Information_Into_Sent_Data]).
weaknesses(signal_Strength_Tracking, [insertion_of_Sensitive_Information_Into_Sent_Data]).
weaknesses(tcp_SYN_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_Connect_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_FIN_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_Xmas_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_Null_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_ACK_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_Window_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(tcp_RPC_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(udp_Scan, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(padding_Oracle_Crypto_Attack, [generation_of_Error_Message_Containing_Sensitive_Information, covert_Channel, improper_Verification_of_Cryptographic_Signature, improper_Validation_of_Integrity_Check_Value, incorrect_Behavior_Order]).
weaknesses(cryptanalysis_of_Cellular_Encryption, [use_of_a_Broken_or_Risky_Cryptographic_Algorithm]).
weaknesses(xml_Routing_Detour_Attacks, [unintended_Proxy_or_Intermediary, externally_Controlled_Reference_to_a_Resource_in_Another_Sphere]).
weaknesses(transaction_or_Event_Tampering_via_Application_API_Manipulation, [modification_of_Assumed_Immutable_Data_MAID, insufficient_Verification_of_Data_Authenticity, origin_Validation_Error, client_Side_Enforcement_of_Server_Side_Security, missing_Encryption_of_Sensitive_Data]).
weaknesses(content_Spoofing_Via_Application_API_Manipulation, [missing_Support_for_Integrity_Check]).
weaknesses(navigation_Remapping_To_Propagate_Malicious_Content, [modification_of_Assumed_Immutable_Data_MAID, insufficient_Verification_of_Data_Authenticity, origin_Validation_Error, client_Side_Enforcement_of_Server_Side_Security, missing_Encryption_of_Sensitive_Data]).
weaknesses(aplication_API_Button_Hijacking, [modification_of_Assumed_Immutable_Data_MAID, insufficient_Verification_of_Data_Authenticity, origin_Validation_Error, client_Side_Enforcement_of_Server_Side_Security, missing_Encryption_of_Sensitive_Data]).
weaknesses(leveraging_Active_Man_in_the_Middle_Attacks_to_Bypass_Same_Origin_Policy, [channel_Accessible_by_Non_Endpoint]).
weaknesses(establish_Rogue_Location, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(sniffing_Attacks, [missing_Encryption_of_Sensitive_Data]).
weaknesses(cryptanalysis, [use_of_a_Broken_or_Risky_Cryptographic_Algorithm, use_of_a_Risky_Cryptographic_Primitive, use_of_Predictable_Algorithm_in_Random_Number_Generator, cryptographic_Operations_are_run_Before_Supporting_Units_are_Ready]).
weaknesses(reflection_Attack_in_Authentication_Protocol, [broken_Authentication_and_Session_Management, incorrect_Implementation_of_Authentication_Algorithm]).
weaknesses(data_Serialization_External_Entities_Blowup, [improper_Restriction_of_XML_External_Entity_Reference]).
weaknesses(eavesdropping, [exposure_of_Sensitive_Information_to_an_Unauthorized_Actor]).
weaknesses(manipulating_Opaque_Client_based_Data_Tokens, [missing_Support_for_Integrity_Check, cleartext_Storage_of_Sensitive_Information_in_a_Cookie, improper_Authorization, session_Fixation, improper_Handling_of_Parameters]).



